directories:
  output: release
  buildResources: build
appId: com.cashier.app
productName: Local Cashier App
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
win:
  target: nsis
nsis:
  oneClick: true
  allowToChangeInstallationDirectory: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 31.0.0
