// Central icon map — single source of truth for every glyph used across the app.
// Replaces all emoji. Swap the library here without touching any screen.
// Implemented over lucide-react.
import {
    LayoutDashboard,
    UtensilsCrossed,
    ReceiptText,
    Settings,
    LogOut,
    ShoppingCart,
    Package,
    Wallet,
    Coins,
    CreditCard,
    ClipboardList,
    Users,
    ShieldCheck,
    Ban,
    Plus,
    Minus,
    Trash2,
    Save,
    Download,
    Upload,
    Search,
    X,
    ChevronDown,
    ChevronUp,
    Printer,
    AlertTriangle,
    Check,
    Clock,
    Boxes,
    TrendingUp,
    DollarSign,
    History,
    UserRound,
    Lock,
    Eye,
    EyeOff,
    RefreshCw,
    Archive,
    Gauge,
    Zap,
    Calendar,
    CalendarRange,
    Infinity as InfinityIcon,
} from 'lucide-react';

const icons = {
    dashboard: LayoutDashboard,
    menu: UtensilsCrossed,
    receipt: ReceiptText,
    settings: Settings,
    logout: LogOut,
    cart: ShoppingCart,
    package: Package,
    wallet: Wallet,
    coins: Coins,
    card: CreditCard,
    clipboard: ClipboardList,
    users: Users,
    shield: ShieldCheck,
    ban: Ban,
    plus: Plus,
    minus: Minus,
    trash: Trash2,
    save: Save,
    download: Download,
    upload: Upload,
    search: Search,
    close: X,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    printer: Printer,
    warning: AlertTriangle,
    check: Check,
    clock: Clock,
    boxes: Boxes,
    trending: TrendingUp,
    cash: DollarSign,
    history: History,
    user: UserRound,
    lock: Lock,
    eye: Eye,
    eyeOff: EyeOff,
    refresh: RefreshCw,
    restore: RefreshCw,
    archive: Archive,
    gauge: Gauge,
    zap: Zap,
    calendar: Calendar,
    calendarRange: CalendarRange,
    infinity: InfinityIcon,
};

// eslint-disable-next-line react-refresh/only-export-components
export default icons;
export {
    LayoutDashboard,
    UtensilsCrossed,
    ReceiptText,
    Settings,
    LogOut,
    ShoppingCart,
    Package,
    Wallet,
    Coins,
    CreditCard,
    ClipboardList,
    Users,
    ShieldCheck,
    Ban,
    Plus,
    Minus,
    Trash2,
    Save,
    Download,
    Upload,
    Search,
    X,
    ChevronDown,
    ChevronUp,
    Printer,
    AlertTriangle,
    Check,
    Clock,
    Boxes,
    TrendingUp,
    DollarSign,
    History,
    UserRound,
    Lock,
    Eye,
    EyeOff,
    RefreshCw,
    Archive,
    Gauge,
    Zap,
    Calendar,
    CalendarRange,
    InfinityIcon,
};